GCC = cc68x

OBJ = raster.o model.o

tst_exc: $(OBJ)
	$(GCC) -g raster.o -o tst
	$(GCC) -g model.o -o mod

raster.o: raster.c raster.h
	$(GCC) -g -c raster.c
	
model.o: model.c model.h
	$(GCC) -g -c model.c
